spring:
  jpa:
    open-in-view: false   # 템플릿 view 화면의 렌더링이 끝날 때 까지 Lazy fetch 가 가능하도록 해주는 속성
    show-sql: true
    hibernate:
      # create / create-drop / update / validate / none
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.H2
      format_sql: true
      use_sql_comments: true
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          lob:
            non_contextual_creation: true # postgres 사용시 createLob() 미구현 경고 삭제


  datasource:
    url: jdbc:h2:mem:inpixdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #initialization-mode: always  # embeded / always
    #platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  devtools:
    livereload:
      enabled: true

logging:
  charset:
    console: UTF-8
  level:
    root: info
    org.hibernate.type: trace