spring:
  jpa:
    open-in-view: false   # 템플릿 view 화면의 렌더링이 끝날 때 까지 Lazy fetch 가 가능하도록 해주는 속성
    show-sql: true
    hibernate:
      # create / create-drop / update / validate / none
      ddl-auto: validate

    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          lob:
            non_contextual_creation: true # postgres 사용시 createLob() 미구현 경고 삭제


  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: inpix
    password: pass
    #driver-class-name: org.postgresql.Driver

  devtools:
    livereload:
      enabled: true

logging:
  charset:
    console: UTF-8
  level:
    root: info
    org.hibernate.type: trace